baseurl: '/'
permalink: pretty
title: 'Medical Device Club'

GOOGLE_ANALYTICS_ID: G-314DLWLHC2

logo:
  mobile: "assets/vanderbilt/images/v/primary/Dimensional_V.png"
  mobile_height: "32px"
  mobile_width: "32px"
  desktop: "assets/vanderbilt/images/primary_lockup/Dimensional_V_Black_Lockup.png"
  desktop_height: "54px"
  desktop_width: "250px"

collections_dir: collections
collections:
  - projects
  - team

sass:
  style: compressed # possible values: nested expanded compact compressed
  quiet_deps: true

plugins:
  - jekyll-environment-variables

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - LICENSE.md
  - LICENSE
  - README.md
