baseurl: '/'
permalink: pretty
title: 'Medical Device Club'

GOOGLE_ANALYTICS_ID: G-314DLWLHC2

logo:
  mobile: "images/logo/Vanderbilt_V.png"
  mobile_height: "32px"
  mobile_width: "32px"
  desktop: "images/logo/Vanderbilt_V.png"
  desktop_height: "100px"
  desktop_width: "100px"

collections:
  projects:
    output: false
  team:
    output: false

defaults:
  - scope:
      path: ""
      type: "projects"
    values:
      layout: "project"
  - scope:
      path: ""
      type: "team"
    values:
      layout: "team"

sass:
  style: compressed # possible values: nested expanded compact compressed
  quiet_deps: true

plugins:
  - jekyll-environment-variables

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - LICENSE.md
  - LICENSE
  - README.md
